---
title: "Data Import"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

Lte's import a data set. 
```{r}
litters_df = 
  read_csv("data/FAS_litters.csv")
```

Look at your data. 
```{r}
names(litters_df)
```

Update names in litters_df
```{r}
litters_df = 
  janitor::clean_names(litters_df)
```

Look at data again (lol)
```{r}
litters_df
```

Skimming data can be nice
```{r}
skimr::skim(litters_df)
```

## Fix the missingness
```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv", 
    na = c("NA", ".", "")
    )
litters_df = 
  janitor::clean_names(litters_df)
```

Import pups and skip first 3 empty rows
```{r}
pups_df = 
  read_csv(
    "data/FAS_pups.csv", 
    na = c("NA", ".", ""), 
    skip = 3
    )
pups_df = 
  janitor::clean_names(pups_df)
```

## Excel imports?
csvs are great but excel files also exist (boo)
```{r}
mlb_df = 
  read_excel("data/mlb11.xlsx")
```

And when the data set is stored in an unorderly fashion use range
```{r}
fotr_df = 
  read_excel("data/LotR_Words.xlsx", range = "B3:D6")
```


## SAS??
Import pulse data set
```{r}
pulse_df = 
  read_sas("data/public_pulse_data.sas7bdat")
pulse_df = 
  janitor::clean_names(pulse_df)
```

## Why we don't use read.csv
```{r, eval = FALSE}
litters_df_base = 
  read.csv("data/FAS_litters.csv")
```

 